import type { Ticket } from "@/types/ticket";

export const TICKETS: Ticket[] = [
  {
    id: "TKT-0041",
    subject: "Cannot access my account — locked out after password reset",
    status: "open",
    priority: "critical",
    category: "account",
    from: "Sarah Chen",
    email: "s.chen@acmecorp.com",
    time: "4m ago",
    sla: 92,
    body: "I reset my password yesterday and now I can't log in at all. It just says 'invalid credentials' but I'm using the new password from the email. I've tried 3 times and now it says my account is locked. This is blocking me from accessing the dashboard for an important client call in 2 hours.",
    triage: null,
  },
  {
    id: "TKT-0040",
    subject: "API rate limit errors on webhook delivery",
    status: "open",
    priority: "high",
    category: "technical",
    from: "Marcus Webb",
    email: "m.webb@devco.io",
    time: "23m ago",
    sla: 78,
    body: "We're seeing consistent 429 errors on our webhook endpoint since about 10am UTC today. Our traffic hasn't changed — we're well within the documented 1000 req/min limit. The errors started around the same time as your maintenance window notification. Error header shows: X-RateLimit-Remaining: 0 but our usage dashboard shows 340 req/min.",
    triage: null,
  },
  {
    id: "TKT-0039",
    subject: "Charged twice for Pro subscription in October",
    status: "open",
    priority: "high",
    category: "billing",
    from: "Priya Nair",
    email: "priya@startupco.com",
    time: "1h ago",
    sla: 65,
    body: "I was charged $49 twice on Oct 14th. My bank statement shows two identical charges from your company within 4 minutes of each other. I only have one account. Can you refund the duplicate charge? My account email is priya@startupco.com.",
    triage: null,
  },
  {
    id: "TKT-0038",
    subject: "Export to CSV missing columns",
    status: "pending",
    priority: "medium",
    category: "technical",
    from: "Tom Fielding",
    email: "tf@blueprint.io",
    time: "2h ago",
    sla: 55,
    body: "When I export my projects to CSV the 'assigned_to' and 'due_date' columns are missing. This worked last week. I need these for a report I'm building in Excel. Using Chrome 118 on macOS.",
    triage: {
      category: "technical",
      priority: "medium",
      sentiment: "frustrated",
      tags: ["export", "csv", "regression", "data"],
      summary:
        "User reports missing columns in CSV export that previously worked. Likely regression from recent release.",
      suggestedResponse:
        "Thanks for reporting this, Tom. We've confirmed the CSV export issue affecting 'assigned_to' and 'due_date' columns — it's a regression introduced in our v2.4.1 release yesterday. Our team is working on a hotfix. In the meantime, you can use the JSON export which contains all fields. I'll update you as soon as the fix ships, likely within 24 hours.",
    },
  },
  {
    id: "TKT-0037",
    subject: "Need to add 5 more seats to our team plan",
    status: "open",
    priority: "medium",
    category: "billing",
    from: "Jordan Kim",
    email: "j.kim@nexus.co",
    time: "3h ago",
    sla: 48,
    body: "We're growing and need to upgrade from 10 seats to 15 seats on our Business plan. Can you tell me the pricing and process? Also, would the new seats be prorated for the rest of the billing cycle?",
    triage: {
      category: "billing",
      priority: "medium",
      sentiment: "positive",
      tags: ["upgrade", "seats", "pricing", "expansion"],
      summary:
        "Customer looking to expand seats — upsell opportunity. Positive sentiment, proactive outreach.",
      suggestedResponse:
        "Great news, Jordan! Adding 5 seats to your Business plan is straightforward. The additional seats are $18/seat/month, prorated from today through your renewal date. I can process the upgrade right now — just confirm and the new seats will be available instantly.",
    },
  },
  {
    id: "TKT-0036",
    subject: "Two-factor authentication not sending SMS codes",
    status: "open",
    priority: "high",
    category: "account",
    from: "Alex Romero",
    email: "a.romero@globalinc.com",
    time: "4h ago",
    sla: 40,
    body: "My 2FA codes stopped coming through to my phone number +1-555-xxx-4892. I've waited up to 10 minutes and nothing arrives. The backup codes aren't working either. I'm completely locked out. This started happening after your system maintenance last night.",
    triage: null,
  },
  {
    id: "TKT-0035",
    subject: "Feature request: bulk assign tickets",
    status: "pending",
    priority: "low",
    category: "feature",
    from: "Dana Osei",
    email: "d.osei@teamflow.com",
    time: "6h ago",
    sla: 30,
    body: "Would love the ability to select multiple tickets and assign them all to an agent at once. Currently we have to do this one by one which takes a long time on Monday mornings when the queue fills up.",
    triage: {
      category: "feature",
      priority: "low",
      sentiment: "neutral",
      tags: ["feature-request", "bulk-actions", "productivity"],
      summary:
        "Feature request for bulk ticket assignment. Common ask — check backlog for existing ticket.",
      suggestedResponse:
        "Thanks for the suggestion, Dana! Bulk assignment is definitely on our radar — it's actually been requested by a few teams. I've added your vote to our product backlog. I can't promise a timeline yet, but I'll make sure you're notified when it ships. In the meantime, you might find our keyboard shortcut workflow helpful: press 'A' on any ticket to quickly assign without leaving the queue view.",
    },
  },
  {
    id: "TKT-0034",
    subject: "Dashboard loading very slowly since yesterday",
    status: "resolved",
    priority: "medium",
    category: "technical",
    from: "Mei Zhang",
    email: "m.zhang@cloudbase.dev",
    time: "8h ago",
    sla: 100,
    body: "The main dashboard takes 12-15 seconds to load. Before yesterday it was almost instant. Running Chrome 118, no extensions, fast connection.",
    triage: {
      category: "technical",
      priority: "medium",
      sentiment: "frustrated",
      tags: ["performance", "dashboard", "regression"],
      summary:
        "Performance regression on dashboard. Correlated with yesterday deploy. Monitoring shows elevated p99 for dashboard queries.",
      suggestedResponse:
        "Hi Mei, thanks for flagging this. We identified and resolved a performance regression that was affecting dashboard load times — it was introduced in yesterday's deployment and has been patched as of 2pm UTC today. Your dashboard should now be loading normally. If you're still seeing slow loads please let me know and I'll escalate to our infrastructure team.",
    },
  },
];